# Default values for nfs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: quay.io/kubernetes_incubator/nfs-provisioner
  tag: latest
  pullPolicy: IfNotPresent

nfs:
  hostPort: 2049

persistence:
  # Set the NFS provisioner to be the default storage class.
  defaultClass: true
  hostPath: /srv

# Toggle RBAC on and off
rbac:
  enabled: true
